spring.application.name=bw-demo

# Datasource
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://postgres:5432/userposts}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:password}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update


# Kafka
kafka.bootstrap-servers=${SPRING_KAFKA_BOOTSTRAP_SERVERS:kafka:9092}
kafka.topic=user-posts-topic
spring.kafka.consumer.group-id=user-posts-group

# WebClient base URL
webclient.base-url=https://jsonplaceholder.typicode.com

# Logging
logging.level.root=INFO
logging.level.com.example.userposts=DEBUG
